pipeline {
    agent any

    triggers {
        // Cada 30 minutos
        cron('H/30 * * * *')
    }

    environment {
        DOCKER_IMAGE = "garysurco/task-backend"
        DOCKER_TAG = "latest"
        NODE_ENV = "production"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/GARYSURCO/TRABAJO-FINAL.git'
            }
        }

        stage('Instalar dependencias') {
            steps {
                dir('backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Construir imagen Docker') {
            steps {
                dir('backend') {
                     bat 'docker build -t garysurco/cicddockerdiplo .'
                }
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhubpwddiplomado', variable: 'DOCKER_PASSWORD')]) {
                        bat """
                        echo %DOCKER_PASSWORD% | docker login -u garysurco --password-stdin
                        docker push garysurco/cicddockerdiplo
                        """
                    }
                }
            }
        }
    }
}
